name: Build & Deploy to Firebase

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Install Dependencies
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: Build
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: build
    - name: Archive Production
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@master
      with: 
        name: build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v1.5.0
      with:
        args: deploy --only hosting
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
